title: Blog posts by Will Grant
description: >
  Will Grant is a product designer and user experience professional with over 20 years experience overseeing the design, information architecture and usability of web and mobile products that have reached over a billion users.
show_excerpts: true

minima:
  social_links:
    twitter: wgx
    github:  wgx
    linkedin: iamwill

theme: minima
url: "https://blog.willgrant.org"

paginate: 7
paginate_path: /page:num/

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-paginate