title: Blog posts by Will Grant
description: >
  UK-based UX expert with 20+ years experience in global web and mobile product design, accessibility, and usability.
show_excerpts: true

minima:
  social_links:
    github:  wgx

theme: minima
url: "https://blog.willgrant.org"

paginate: 7
paginate_path: /page:num/

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-paginate
